# Generated by Django 5.0.1 on 2024-02-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDimage',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
