# Generated by Django 5.0.1 on 2024-02-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_prdimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDIimage', models.ImageField(default='path/to/default/image.jpg', upload_to='photos/%y/%m/%d')),
                ('PRDIproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name=' product ')),
            ],
        ),
    ]
