# Generated by Django 5.0.1 on 2024-02-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CATdescription',
            field=models.TextField(default='', max_length=50, verbose_name='Category Description'),
        ),
    ]
