# Generated by Django 5.0.1 on 2024-02-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_category_catparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlternatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALTalternative', models.ManyToManyField(related_name='Alternative_Product', to='product.product')),
                ('PALTproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_products', to='product.product')),
            ],
        ),
    ]
