# Generated by Django 5.0.1 on 2024-02-04 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productalternatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCalternative', models.ManyToManyField(related_name='Accessories_Product', to='product.product')),
                ('PACCproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_Accessories', to='product.product')),
            ],
        ),
    ]
