# Generated by Django 5.0.1 on 2024-02-05 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productaccessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATImg',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='Category/%y/%m/%d', verbose_name='Category Image '),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productaccessories',
            name='PACCalternative',
            field=models.ManyToManyField(related_name='Accessories_Product', to='product.product', verbose_name='Alternative Product'),
        ),
        migrations.AlterField(
            model_name='productaccessories',
            name='PACCproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_Accessories', to='product.product', verbose_name='Accessory Name'),
        ),
        migrations.AlterField(
            model_name='productalternatives',
            name='PALTalternative',
            field=models.ManyToManyField(related_name='Alternative_Product', to='product.product', verbose_name='Alternative Product'),
        ),
        migrations.AlterField(
            model_name='productalternatives',
            name='PALTproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_products', to='product.product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='PRDIimage',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='photos/%y/%m/%d', verbose_name='Product Image'),
        ),
    ]
