# Generated by Django 5.0.1 on 2024-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_category_catimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDslug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
