# Generated by Django 5.0.1 on 2024-02-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_prdslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRDslug',
            new_name='PRDSlug',
        ),
    ]
