# Generated by Django 5.0.1 on 2024-02-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_prddescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDdiscount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount Price'),
            preserve_default=False,
        ),
    ]
