# Generated by Django 5.0.1 on 2024-02-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_prddiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDisBestSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDisNew',
            field=models.BooleanField(default=True),
        ),
    ]
