# Generated by Django 5.0.1 on 2024-02-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_prdisbestseller_product_prdisnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDisBestSeller',
            field=models.BooleanField(default=False, verbose_name='Best Seller Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDisNew',
            field=models.BooleanField(default=True, verbose_name='New Product'),
        ),
    ]
