# Generated by Django 5.0.1 on 2024-02-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRDName', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('BRDDescription', models.TextField(max_length=50, verbose_name='Brand Description')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NRTName', models.CharField(max_length=255, verbose_name='Variant Name')),
                ('VRTDescription', models.TextField(max_length=50, verbose_name='Variant Description')),
            ],
        ),
    ]
